### ISSUE TITLE
Hub Auto Bump

### ISSUE THREAD

**Issue by Lan2u** [ents-crew/uems-hub#28]
Ideally, we should set up a script where a new commit being merged into a release branch on one of the git submodules triggers hub to automatically update to the new sub-repo version.

**Comment by Vitineth** [comment]
Want me to have a look at doing this in the next few days?

**Comment by Lan2u** [comment]
Yeah sure

**Comment by Lan2u** [comment]
@Vitineth  completed this using dependabot
